import { StyleSheet } from 'react-native';
import { withSafeAreaInsets } from 'react-native-safe-area-context';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#D0E2FF',
    },
    imagem: {
        width: 340,
        height: 200,
        resizeMode: 'contain',
        borderRadius: 15,
        borderWidth: 7,
        borderColor: "#002D9C",
    },
    baseText: {
        fontWeight: 'bold',
        paddingRight: '20%',
        color: "#002D9C",
        fontSize: 15,
        marginTop: '5%',
        marginBottom: '2%',
      },
      input: {
        height: 40,
        marginLeft: 5,
        borderWidth: 2,
        borderRadius: 12,
        backgroundColor: '#FFF',
        borderColor: '#4589FF',
        paddingStart: 12,
    },
      loginBox: {
        backgroundColor: '#f4f4f4',
        padding: 15,
        maxHeight: '95%',
        maxWidth: '95%',
        marginBottom: 20,
        borderRadius: 15,
        borderColor: 'blue',
        minWidth: '75%',
        justifyContent: 'space-around',
    },
    loginText: {
        padding: 8,
        fontWeight: 'bold',
        fontSize: 15,
        color: "#002D9C",
    },
    btnImagem: {
        marginTop: 10,
        width: 340,
        height: 130,
        resizeMode: 'contain',
        borderRadius: 17,
        borderWidth: 7,
        borderColor: "#002D9C",
        
    },
    btnImagemBig: {
        marginBottom: 20,
        marginTop: 10,
        width: 340,
        height: 150,
        resizeMode: 'contain',
        borderRadius: 17,
        borderWidth: 7,
        borderColor: "#002D9C",
        alignItems: 'center',
    },
    BottomBar: {
        backgroundColor: '#00063A',
        padding: 15,
        height: '10%',
        borderTopLeftRadius:15,
        borderTopRightRadius:15,
        maxWidth: '100%',
        minWidth: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    btnManuten: {
        borderRadius: 15,
        padding: 10,
        marginBottom: 10,
        marginTop: 10,
        backgroundColor: '#4589FF',
        width: 300,
        alignSelf: 'center',
        alignItems: 'center',
    },
    btnConcManuten: {
        borderRadius: 15,
        padding: 10,
        marginBottom: 10,
        marginTop: 10,
        backgroundColor: '#4589FF',
        width: 300,
        alignSelf: 'center',
        alignItems: 'center',
    },
    btnVoltar: {
        borderRadius: 15,
        padding: 10,
        backgroundColor: '#4589FF',
        width: 300,
        marginBottom: 2,
        marginTop: -30,
        alignSelf: 'center',
        alignItems: 'center',
    },
    btnText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: 'white',
    },
    IconTab: {
        
    },
    header: {
        backgroundColor: '#4589FF',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingRight: 10,
        paddingLeft: 10,
        paddingTop: 15,
    },
    logo: {
        width: 120,
        height: 100,
        resizeMode: 'contain',
    },

    perfil: {
        width: 80,
        height: 60,
        resizeMode: 'contain',
    },
    scrollview: {
        alignItems: 'center',
        justifyContent:'space-around',
       },
    mostrar: {
        fontSize: 16,
        marginTop: 8,
        marginRight: 5,
        textAlign: 'right',
    },
    texto: {
        fontSize: 20,
    },
    checkBox: {
        marginTop: '5%',
        borderRadius: 12,
        borderWidth: 2,
        backgroundColor: 'white',
        borderColor: "#002D9C",
        padding: '3%',
    },
});

export default styles;