import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    esquerda: {
        textAlign: 'right',
    },
    direita: {
        alignSelf: 'center',
        position: 'absolute',
        right: 0
    },
    innerCard: {
        maxWidth: '100%',
        flex: 1,
        flexDirection: 'row',
    },
    caixona: {
        backgroundColor: '#fff',
        width: '100%',
        padding: 20,
        alignSelf: 'center',
        borderBottomWidth: 4,
        borderBottomColor: '#CCC',
        flexDirection: 'row',
    },
    botaoCaixona: {
        flexDirection: 'row-reverse',
        alignItems: 'center',
        marginTop: 10,
    },
    botaoEditar: {
        marginLeft: 10,
        backgroundColor: '#D8D8D8',
        borderRadius: 10,
        padding: 10,
        fontSize: 12,
        elevation: 10,
        shadowOpacity: 10,
        shadowColor: '#ccc',
        alignItems: 'center',
    },
    botaoText: {
        color: '#fff',
        fontWeight: 'bold',
    },
    textoNome: {
        fontSize: 20,
    },
    textoEmail: {
        fontSize: 16,
    },
    container: {
        backgroundColor: '#D0E2FF',
    },
    logo: {
        width: 300,
        height: 300,
        resizeMode: 'contain',
    },
    input: {
        height: 40,
        borderWidth: 1,
        borderRadius: 10,
        backgroundColor: '#FFF',
        borderColor: '#4589FF',
        paddingStart: 10,
    },
    listBox: {
        paddingBottom: 120,
        maxWidth: '100%',
        borderRadius: 15,
        minWidth: '75%',
        justifyContent: 'space-around',
    },
    loginText: {
        padding: 5,
        fontSize: 18,
        fontWeight: 'bold',
    },
    btnLogin: {
        marginTop: 20,
        borderRadius: 15,
        padding: 10,
        marginBottom: 10,
        backgroundColor: '#4589Ff',
        maxWidth: '100%',
        minWidth: '30%',
        alignSelf: 'center',
        alignItems: 'center',
    },
    btnRedirect: {
        color: 'white',
        marginTop: 20,
        borderRadius: 15,
        padding: 10,
        marginBottom: 10,
        backgroundColor: '#FF5733',
        maxWidth: '100%',
        minWidth: '30%',
        alignSelf: 'center',
        alignItems: 'center',
    },
    btnText: {
        fontSize: 18,
        fontWeight: 'bold',
    },
    registerText: {
        textDecorationLine: 'underline',
    },
    registerBtn: {
        justifyContent: 'center',
        alignItems: 'center',
        alignContent: 'center',
    },
    buttonNewTask: {
        width: 60,
        height: 60,
        position: 'absolute',
        bottom: 0,
        left: 20,
        backgroundColor: '#F92e6a',
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    iconButton: {
        color: '#ffffff',
        fontSize: 25,
        fontWeight: 'bold',
    },
    container: {
        flex: 1,
        backgroundColor: '#D0E2FF',
    },
    header: {
        backgroundColor: '#4589FF',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingRight: 10,
        paddingLeft: 10,
        paddingTop: 15,
    },
    logo: {
        width: 120,
        height: 100,
        resizeMode: 'contain',
    },

    perfil: {
        width: 80,
        height: 60,
        resizeMode: 'contain',
    },
    BottomBar: {
        backgroundColor: '#00063A',
        padding: 15,
        height: '10%',
        borderTopLeftRadius: 15,
        borderTopRightRadius: 15,
        maxWidth: '100%',
        minWidth: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        position: 'relative',
    },
    loginText: {
        padding: 5,
        fontSize: 18,
        fontWeight: 'bold',
    },
    btnCadastro: {
        marginTop: 15,
        borderRadius: 15,
        padding: 15,
        marginBottom: 10,
        backgroundColor: '#4589FF',
        maxWidth: '80%',
        minWidth: '80%',
        alignSelf: 'center',
        alignItems: 'center',
    },
    input: {
        height: 40,
        borderWidth: 1,
        borderRadius: 10,
        backgroundColor: '#FFF',
        borderColor: '#4589FF',
        paddingStart: 10,
        maxWidth: '90%',
    },
    inputDescricao: {
        height: 100,
        borderWidth: 1,
        borderRadius: 10,
        backgroundColor: '#FFF',
        borderColor: '#4589FF',
        paddingStart: 10,
        borderBottomWidth:1,
        textAlignVertical: 'top',
        padding: 10,
        maxWidth: '90%',
    },
    select: {
        height: 55,
        borderWidth: 1,
        borderRadius: 10,
        backgroundColor: '#FFF',
        borderColor: '#4589FF',
        paddingStart: 10,
    },
    Adicionado: {
        marginTop: '4%',
        textAlign: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        borderWidth: 1,
        borderRadius: 10,
        borderColor: '#4589FF',
        paddingStart: 10,
    },
    loginBox: {
        marginTop: '3%',
        backgroundColor: '#f4f4f4',
        padding: 15,
        maxHeight: '300%',
        maxWidth: '99%',
        borderRadius: 15,
        minWidth: '90%',
    },
    btnText: {
        color: 'white',
        fontWeight: 'bold',
    },
    scrollview: {
        alignItems: 'center',
        justifyContent: 'space-around',
    },
    TextArea: {
        height: 90,
        borderWidth: 1,
        borderRadius: 10,
        backgroundColor: '#FFF',
        borderColor: '#4589FF',
        paddingStart: 10,
    },
});

export default styles;
